### ISSUE TITLE
Assigning neighbors_key in milopy.core.make_nhoods

### ISSUE THREAD

**Issue by sylash92** [emdann/milopy#31]
Hi Emma,

Thank you for developing Milo!

I am currently using scvi-tools to correct for batch effects in my single cell data, and so, as you would probably know very well, my anndata does not have X_pca computed. I was trying to find implementation of using milopy on scvi corrected dataset, and I ran into your work again in the Pan_fetal_immune project. Also thank you very much for that as well. It's been a huge help.

I've run into one issue with assigning neighbors_key as "scvi" in the `milopy.core.make_nhoods()` . I believe there has been an error in line 58 (maybe on line 46 as well) of **milopy/core.py** `use_rep = adata.uns["neighbors"]["params"]["use_rep"]`.  I've just switched out "neighbors" with neighbors_key and it has been fine since.

I hope it could help someone else out as well.
Thank you again,
Seyoon.

**Comment by emdann** [comment]
Hi @sylash92, thank you for spotting this! Fix coming soon
