### ISSUE TITLE
Get all cells of a neighborhood given the index_cell

### ISSUE THREAD

**Issue by vronii-k** [emdann/milopy#32]
Hello,
is there a simple way to determine all cells of a neighborhood by the index cell?
Using the adata.obsm['nhoods'] matrix only works if the index_cell does not belong to another neighborhood. 

Thank you for your help

**Comment by emdann** [comment]
Hi @vronii-k 
The neighbourhoods in `adata.obsm['nhoods']` are ordered by the order of the index cells defined by the binary variable `adata.obs['nhood_ixs_refined']`. So if you want to pick all the cells from the neighbourhood of a specific index cell (`ix_cell`) you can do something like this - using Quick start example from the README:
```
ix_cell = 'AAAGAGACGGACTT-1'
all_index_cells = adata.obs_names[adata.obs['nhood_ixs_refined']==1]
cells_in_ix_cell_nhood = adata.obsm['nhoods'][:, all_index_cells == ix_cell].toarray() == 1
```

**Comment by vronii-k** [comment]
Thank you @emdann! That worked :)
