### ISSUE TITLE
Unable to save adata.uns["nhood_adata"]

### ISSUE THREAD

**Issue by jan-domke** [emdann/milopy#5]
If I run the complete milo pipeline and want to save all results in the end using ```adata.write(path)``` I get the following error:

```
NotImplementedError: Failed to write value for uns/nhood_adata, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.
Above error raised while writing key 'uns/nhood_adata' of <class 'h5py._hl.files.File'> from /.
```

Even if I save the adata.uns["nhood_adata"] separately ( ```adata_save = adata.uns["nhood_adata"]``` and then ```adata_save.write(path)```) I get an error and only the ```obs``` and ```var``` parts are saved, the others are ignored:
```
ValueError: Unable to create dataset (name already exists)
Above error raised while writing key '__categories/sample' of <class 'h5py._hl.group.Group'> from /.
Above error raised while writing key 'sample' of <class 'h5py._hl.group.Group'> from /.
Above error raised while writing key 'var' of <class 'h5py._hl.files.File'> from /.
```

**Comment by emdann** [comment]
Hi @jan-domke, thanks for flagging this. 

As far as I know, there is no implementation for a nested AnnData structure in `anndata`, so far I've hacked my way around this big time with:
```
nhood_adata = adata.uns["nhood_adata"].copy()
del adata.uns["nhood_adata"]
adata.write_h5ad("./test_milopy_adata.h5ad")
nhood_adata.write_h5ad("./test_milopy_adata.nhoods.h5ad")
```
For now I'm adding a line for saving in the tutorial, I'll look more into the `anndata` and `h5py` capabilities to see if there's an alternative for saving results in one place.

This works for me in the examples, I'm not able to reproduce the errors downstream. Do you get these running the [tutorial](https://nbviewer.org/github/emdann/milopy/blob/master/notebooks/milopy_example.ipynb)? If not what is the structure of the object in `adata.uns["nhood_adata"]`? And what is the output of `adata.uns["nhood_adata"].obs.dtypes` and `adata.uns["nhood_adata"].var.dtypes`?

**Comment by emdann** [comment]
Added read/write utils to save cell x gene anndata and associated nhood x sample adata with https://github.com/emdann/milopy/pull/12
