### ISSUE TITLE
Retrieving adata.obs_names belonging to each adata.uns["nhood_adata"].obs_names

### ISSUE THREAD

**Issue by castaway1990** [emdann/milopy#6]
Hi, is there a way to know which original cells are making each neighborhood?

Thanks!

**Comment by castaway1990** [comment]
Right, thanks a lot.

**Comment by emdann** [comment]
or if you are referring to the index cell for each neighbourhood, these are marked in `adata.obs['nhood_ixs_refined']` and the order of columns in `adata.obsm['nhoods']` is the same as in `obs` (i.e. the first cell where `adata.obs['nhood_ixs_refined']==1` is index to the nhood in the first column in `adata.obsm['nhoods']`)
