### ISSUE TITLE
plotNhoodGraphDA in python version

### ISSUE THREAD

**Issue by alitinet** [emdann/milopy#7]
Hi all,

is it possible to get the same plot as with `plotNhoodGraphDA()` in R in the python version too? I'm aware of `milopy.plot.plot_nhood_graph()` but it's not as pretty :) Thanks!

**Comment by emdann** [comment]
If it's just that then you can simply put `plot_edges=True` in `plot_nhood_graph`. Apparently I had put in this option and I didn't even remember it 😅  From the vignette:
```
milopl.plot_nhood_graph(adata, 
                        alpha=0.01, ## SpatialFDR level (1%) 
                        min_size=2, ## Size of smallest dot
                        plot_edges=True
                       )
```
![Screenshot 2022-05-23 at 16 06 02](https://user-images.githubusercontent.com/32264060/169849790-4bd0a599-853f-4e2e-a245-4f25634acdb0.png)

What's missing compared to the R version would be edge thickness proportional to the overlap, although I have rarely find that to be particularly insightful, as it is often obscured by overplotting. Then adding legends for points size (i.e. no of cells in nhoods) would be desirable, I can look into this, any suggestion is welcome.

**Comment by alitinet** [comment]
Oh this is great already, I also didn't notice there was an option to add edges! Thanks for pointing this out!
